### ISSUE TITLE
Meetup API Key Method No Longer Works

### ISSUE THREAD

**Issue by mzagaja** [codeforboston/cfb-hack-night-form-fill#1]
```
019-08-27T05:00:56.117675+00:00 app[scheduler.1021]: '401 - {"errors":[{"code":"auth_fail","message":"Invalid api key"}]}',
2019-08-27T05:00:56.117677+00:00 app[scheduler.1021]: stack:
2019-08-27T05:00:56.117679+00:00 app[scheduler.1021]: 'StatusCodeError: 401 - {"errors":[{"code":"auth_fail","message":"Invalid api key"}]}\n    at new StatusCodeError (/app/node_modules/request-promise-core/lib/errors.js:32:15)\n    at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:104:33)\n    at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at Request.self.callback (/app/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:189:13)\n    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:189:13)\n    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:277:13)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' } } }
2019-08-27T05:37:28.457480+00:00 heroku[web.1]: Idling
2019-08-27T05:37:28.471430+00:00 heroku[web.1]: State changed from up to down
2019-08-27T05:37:32.959667+00:00 heroku[web.1]: Stopping all processes with SIGTERM
2019-08-27T05:37:33.052930+00:00 heroku[web.1]: Process exited with status 143
```
Sad trombone. Would someone be able to submit a PR to get this to work with the new OAuth 2 authentication method and Meetup?

**Comment by logankilpatrick** [comment]
Will take a look tonight and see if I can fix it!
